sudo: false
language: python


python:
  - "2.7"
  - "pypy"

install:
    - pip install -r test-requirements.txt

script:
    - py.test --cov=shiki tests

after_success:
    - bash <(curl -s https://codecov.io/bash)
